# name=input("enter name:")
# age=int(input("enter age:"))
# DOB=input("enter dob(YY-MM-DD):")
# father_name=input("enter father name:")
# mother_name=input("enter mother name:")
# address=input("enter address:")
# phonenumber=int(input("enter phone number:"))
# email=input("enter mail:")
# print("Your details are:")
# print("NAME:",name)
# print("AGE:",age)
# print("DATE OF BIRTH:",DOB)
# print("FATHER'S NAME:",father_name)
# print("MOTHER'S NAME:",mother_name)
# print("ADDRESS:",address)
# print("PHONE NUMBER:",phonenumber)
# print("EMAIL ID:",email)